- name: Directory is present
  file:
    path=/data/books-service/db
    state=directory
  tags: [books-service]

- name: Latest container is pulled
  shell: sudo docker pull 192.168.50.91:5000/books-service
  tags: [books-service]

- name: Container is absent
  docker_container:
    image=192.168.50.91:5000/books-service
    name=books-service
    state=absent
  tags: [books-service]

- name: Container is running
  docker_container:
    name=books-service
    image=192.168.50.91:5000/books-service
    ports=9001:8080
    volumes=/data/books-service/db:/data/db
    state=running
  tags: [books-service]
