- name: Add Docker repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    update_cache: yes
    state: present
  tags: [docker]

- name: Docker is present
  apt:
    name: docker-engine
    state: latest
    force: yes
  tags: [docker]

- name: Python-pip is present
  apt: name=python-pip state=present
  tags: [docker]

- name: Debian docker-py is present
  pip:
    name: docker-py
    version: 1.6.0
    state: present
  tags: [docker]

- name: Files are present
  copy:
    src: docker
    dest: /etc/default/docker
  register: copy_result
  tags: [docker]

- name: Docker service is restarted
  service:
    name: docker
    state: restarted
  when: copy_result|changed
  tags: [docker]
